[2024-12-12T05:06:57.268+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T05:06:57.276+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9843500346_2024-12-12T05-01-28-818169Z.branch_on_call_status scheduled__2024-12-12T05:01:28.818169+00:00 [queued]>
[2024-12-12T05:06:57.280+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9843500346_2024-12-12T05-01-28-818169Z.branch_on_call_status scheduled__2024-12-12T05:01:28.818169+00:00 [queued]>
[2024-12-12T05:06:57.280+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-12T05:06:57.285+0000] {taskinstance.py:2889} INFO - Executing <Task(_BranchPythonDecoratedOperator): branch_on_call_status> on 2024-12-12 05:01:28.818169+00:00
[2024-12-12T05:06:57.290+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=38302) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-12T05:06:57.291+0000] {standard_task_runner.py:72} INFO - Started process 38303 to run task
[2024-12-12T05:06:57.292+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9843500346_2024-12-12T05-01-28-818169Z', 'branch_on_call_status', 'scheduled__2024-12-12T05:01:28.818169+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpy560euum']
[2024-12-12T05:06:57.292+0000] {standard_task_runner.py:105} INFO - Job 415: Subtask branch_on_call_status
[2024-12-12T05:06:57.315+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9843500346_2024-12-12T05-01-28-818169Z.branch_on_call_status scheduled__2024-12-12T05:01:28.818169+00:00 [running]> on host 1868de310944
[2024-12-12T05:06:57.359+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9843500346_2024-12-12T05-01-28-818169Z' AIRFLOW_CTX_TASK_ID='branch_on_call_status' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T05:01:28.818169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T05:01:28.818169+00:00'
[2024-12-12T05:06:57.359+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T05:06:57.361+0000] {python.py:240} INFO - Done. Returned value was: find_if_proper_interaction_is_completed
[2024-12-12T05:06:57.361+0000] {branch.py:38} INFO - Branch into find_if_proper_interaction_is_completed
[2024-12-12T05:06:57.361+0000] {skipmixin.py:230} INFO - Following branch ('find_if_proper_interaction_is_completed',)
[2024-12-12T05:06:57.368+0000] {skipmixin.py:278} INFO - Skipping tasks [('find_reason_for_unanswered', -1)]
[2024-12-12T05:06:57.382+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T05:06:57.382+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9843500346_2024-12-12T05-01-28-818169Z, task_id=branch_on_call_status, run_id=scheduled__2024-12-12T05:01:28.818169+00:00, execution_date=20241212T050128, start_date=20241212T050657, end_date=20241212T050657
[2024-12-12T05:06:57.424+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-12T05:06:57.439+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-12T05:06:57.440+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
