[2024-12-14T04:51:42.870+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-14T04:51:42.880+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9863818037_2024-12-14T04-48-15-235285Z.check_if_callerid_is_present_in_calllogs_table scheduled__2024-12-14T04:48:15.235285+00:00 [queued]>
[2024-12-14T04:51:42.883+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9863818037_2024-12-14T04-48-15-235285Z.check_if_callerid_is_present_in_calllogs_table scheduled__2024-12-14T04:48:15.235285+00:00 [queued]>
[2024-12-14T04:51:42.883+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-14T04:51:42.889+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): check_if_callerid_is_present_in_calllogs_table> on 2024-12-14 04:48:15.235285+00:00
[2024-12-14T04:51:42.894+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76952) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T04:51:42.895+0000] {standard_task_runner.py:72} INFO - Started process 76953 to run task
[2024-12-14T04:51:42.895+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9863818037_2024-12-14T04-48-15-235285Z', 'check_if_callerid_is_present_in_calllogs_table', 'scheduled__2024-12-14T04:48:15.235285+00:00', '--job-id', '510', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpvl87sgqn']
[2024-12-14T04:51:42.895+0000] {standard_task_runner.py:105} INFO - Job 510: Subtask check_if_callerid_is_present_in_calllogs_table
[2024-12-14T04:51:42.919+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9863818037_2024-12-14T04-48-15-235285Z.check_if_callerid_is_present_in_calllogs_table scheduled__2024-12-14T04:48:15.235285+00:00 [running]> on host 1868de310944
[2024-12-14T04:51:42.958+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9863818037_2024-12-14T04-48-15-235285Z' AIRFLOW_CTX_TASK_ID='check_if_callerid_is_present_in_calllogs_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T04:48:15.235285+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T04:48:15.235285+00:00'
[2024-12-14T04:51:42.959+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-14T04:51:42.964+0000] {base.py:84} INFO - Retrieving connection 'aicallagent'
[2024-12-14T04:51:42.970+0000] {sql.py:544} INFO - Running statement: SELECT * FROM call_logs WHERE caller_id = 'demo-scheduled-from-ui-global8efe1262-4f73-4512-bd08-f454d3b26898' limit 1;, parameters: None
[2024-12-14T04:51:42.972+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-14T04:51:42.973+0000] {python.py:240} INFO - Done. Returned value was: answered
[2024-12-14T04:51:42.985+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-14T04:51:42.985+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9863818037_2024-12-14T04-48-15-235285Z, task_id=check_if_callerid_is_present_in_calllogs_table, run_id=scheduled__2024-12-14T04:48:15.235285+00:00, execution_date=20241214T044815, start_date=20241214T045142, end_date=20241214T045142
[2024-12-14T04:51:43.028+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-14T04:51:43.033+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
